services:
  postgres:
    container_name: room-booking-postgres
    image: postgres:16.2
    environment:
      POSTGRES_USER: room_booking
      POSTGRES_PASSWORD: room_booking
      POSTGRES_DB: room_booking_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - room_booking_network
    restart: unless-stopped

  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "room_booking_rabbitmq"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"

networks:
  room_booking_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
